<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-14T12:09:45 IST" name="Default suite" finished-at="2024-02-14T12:11:15 IST" duration-ms="90431">
    <groups>
    </groups>
    <test started-at="2024-02-14T12:09:45 IST" name="Default test" finished-at="2024-02-14T12:11:15 IST" duration-ms="90431">
      <class name="Error.Console_log.Colab_consolelog">
        <test-method is-config="true" signature="setup()[pri:0, instance:Error.Console_log.Colab_consolelog@59505b48]" started-at="2024-02-14T12:09:45 IST" name="setup" finished-at="2024-02-14T12:09:47 IST" duration-ms="1986" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:1, instance:Error.Console_log.Colab_consolelog@59505b48]" started-at="2024-02-14T12:09:47 IST" name="login" finished-at="2024-02-14T12:09:55 IST" duration-ms="8171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="seriesset_API()[pri:2, instance:Error.Console_log.Colab_consolelog@59505b48]" started-at="2024-02-14T12:09:55 IST" name="seriesset_API" finished-at="2024-02-14T12:09:55 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- seriesset_API -->
        <test-method signature="goatBrain()[pri:3, instance:Error.Console_log.Colab_consolelog@59505b48]" started-at="2024-02-14T12:09:55 IST" name="goatBrain" finished-at="2024-02-14T12:10:26 IST" duration-ms="31206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goatBrain -->
        <test-method signature="mouseBrain()[pri:4, instance:Error.Console_log.Colab_consolelog@59505b48]" started-at="2024-02-14T12:10:26 IST" name="mouseBrain" finished-at="2024-02-14T12:11:15 IST" duration-ms="48905" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[SEVERE logs were found in the console. expected [0] but found [10]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: SEVERE logs were found in the console. expected [0] but found [10]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at Error.Console_log.Colab_consolelog.checkConsoleLog(Colab_consolelog.java:307)
at Error.Console_log.Colab_consolelog.mouseBrain(Colab_consolelog.java:284)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mouseBrain -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:Error.Console_log.Colab_consolelog@59505b48]" started-at="2024-02-14T12:11:15 IST" name="afterTest" finished-at="2024-02-14T12:11:15 IST" duration-ms="125" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Error.Console_log.Colab_consolelog -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
